### ISSUE TITLE
IESG Barry Leiba: Section 7.7

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#181]
— Section 7.7 —

   behaviour (ie. match - replace - delete communities on administrative
   boundaries).

I can’t understand what’s in the parentheses, nor even whether “i.e.” is correct or it should be “e.g.”.

**Comment by suehares** [comment]
Old/Operators are encouraged to make use of the BGP policy framework
   supported by their implementation in order to achieve a predictable
   behaviour (ie. match - replace - delete communities on administrative
   boundaries)./
New/Operators are encouraged to make use of the BGP policy framework 
 supported by their implementation to achieve a predictable behavior./  

We do not need the remainder of the sentence.

**Comment by stoffi92** [comment]
//doc
New/Operators are encouraged to make use of the BGP policy framework
supported by their implementation to achieve a predictable behavior./
