### ISSUE TITLE
IESG Benjamin Kaduk: Security. this this this

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#212]
provide service (unfiltered address space hijack).  Since validation
   of the Flow Specification is tied to the announcement of the best
   unicast route, this may also cause this validation to fail and
   consequently prevent Flow Specifications from being accepted by a
   peer.  Possible mitigations are [RFC6811] and [RFC8205].

nit: there's a lot of pronouns ("this") in here; it might be worth
disambiguating a couple.

**Comment by suehares** [comment]
A rewrite for this sentence would be helpful. 
Here's one:
New:/Since validation of the Flow Specification is tied to the announcement of 
the best unicast route, the failure in the validation of best path route may prevent the 
Flow Specificaiton from being accepted by a peer./

Please ask Robert to review this suggestion.

**Comment by stoffi92** [comment]
@raszuk can you please comment on that.

**Comment by raszuk** [comment]
To be precise we will still accept it, but just not used for best path.

s/ from being accepted by a peer/ from being used by a local router/
