### ISSUE TITLE
783	   BGP implementations MUST also enforce that the AS_PATH attribute of a

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#60]
783	   BGP implementations MUST also enforce that the AS_PATH attribute of a
784	   route received via the External Border Gateway Protocol (eBGP)
785	   contains the neighboring AS in the left-most position of the AS_PATH
786	   attribute.  While this rule is optional in the BGP specification, it
787	   becomes necessary to enforce it for security reasons.

[major] Is this requirement only for the Flow Specification AFI/SAFI pairs, or for all address families (IPv4 in the case of this document)?  Why?

[major] [Assuming that the answer to the last question is: "Yes, for all AFs"...] Should all the border routers in the AS enforce the first ASN, or is the requirement only for routers receiving Flow Specifications?

[major] In the case of receiving Flow Specifications from a neighbor in an IXP, it may not be possible to enforce the rule above if a "transparent ASN" is being used.  Please include some text/guidance about that type of case.  Include it either here or in the Security Considerations.

[nit] The mention of security above makes me want to see related considerations in §13/14.

**Comment by raszuk** [comment]
This paragraph is about all AFI/SAFIs which flow spec can act on so 1/1 and 1/128 + of course the flow spec itself 1/133 & 1/134.  That recommendation is for all routers in the domain as we must make sure that some other AS did not injected more specific unicast route. 

In the case of IXP indeed this sometime may break in the cases where RS is used. If you even in the IX (which is L2 typically) use direct EBGP session it all works ok. If you use session to RS and such RS by design is transparent in order to not extend the AS_PATH length that enforce first AS should be  disabled. I think we could say that use of flow spec when peering with RS in IXP env is much less secure as ASN spoofing in the AS-PATH can occur. It is advised to apply strict inbound route policy in such scenarios.
