### ISSUE TITLE
795	   Explanation:

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#62]
795	   Explanation:

797	   The underlying concept is that the neighboring AS that advertises the
798	   best unicast route for a destination is allowed to advertise flow-
799	   spec information that conveys a more or equally specific destination
800	   prefix.  Thus, as long as there are no more specific unicast routes,
801	   received from a different neighboring AS, which would be affected by
802	   that filtering rule.

804	   The neighboring AS is the immediate destination of the traffic
805	   described by the Flow Specification.  If it requests these flows to
806	   be dropped, that request can be honored without concern that it
807	   represents a denial of service in itself.  Supposedly, the traffic is
808	   being dropped by the downstream autonomous system, and there is no
809	   added value in carrying the traffic to it.

[major] A rogue router may request the traffic to be dropped.  While the local AS is simply reacting to the neighbor's request, the action can still result in a DoS.  I would like to see rogue router scenarios reflected in the Security Considerations.

[major] All this section seems to assume that flows are controlled (dropped/redirected) between ASes...but the actions can also be triggered from inside an AS.  What are the considerations in that case?  Why isn't iBGP explicitly considered?

**Comment by stoffi92** [comment]
> [major] A rogue router may request the traffic to be dropped. While the local AS is simply reacting to the neighbor's request, the action can still result in a DoS. I would like to see rogue router scenarios reflected in the Security Considerations.

This has already been addressed in #9

> [major] All this section seems to assume that flows are controlled (dropped/redirected) between ASes...but the actions can also be triggered from inside an AS. What are the considerations in that case? Why isn't iBGP explicitly considered?

In the iBGP case we are basically validating ourselves (which from the specification is fine, but I think pretty much all implementations have a knob to turn this off entirely - and there is a FS draft draft-ietf-idr-bgp-flowspec-oid that relaxes the ibgp case). Compared to iBGP for ipv4 unicast: We very seldom care about what we receive from our own iBGP neighbors or RRs. We usually care about what we receive from outside our administrative domain (ig. eBGP). Furthermore in the iBGP case we do not have any origin AS to verify against. The rough system is now addressed in the security considerations.

**Comment by suehares** [comment]
Christoph: 
We have the draft-ietf-idr-bgp-flowspec-oid-10.txt specification for the AT&T case that relaxes the ibgp specification.  The authors would prefer to put thier changes in the FS specification.  

We need to annotate this pointing toward the BGP oid specification for the specific IBGP case. 
Putting this in the security consideration section.  

Old:/ Where the above mechanisms are not in place, this would open the door
   to further denial-of-service attacks such as unwanted traffic filtering,
   remarking or redirection./
New: /<t> Where the above mechanisms are not in place, this could open the door 
to furhter denial-of-service attacks such as unwanted traffic filtering, 
remarking, or redirection.  
</t>
<t> One proposal for relaxing the above mechanisms  within the administrative 
boundaries of AS via ibgp is included in [draft-ietf-idr-bgp-oid].  
Deployment of such specific relaxation of validation within an 
adminstrative boundary of a network defined by an AS or an
AS-Confederation boundary may useful in some network in 
quickly distributing filters to prevent denial-of-service attacks.  
For a network to utilize this relaxation,  the BGP policies must 
support additional filtering since the the origin as field is empty. 
Specifications relaxing the validation restrictions SHOULD 
contain security considerations that provide details on the 
required additional filtering. 
</t> 

--- please review this text and see if it is acceptable to you.   If so, close the issue

**Comment by stoffi92** [comment]
fine.

**Comment by stoffi92** [comment]
//doc
Major1:
Has been addressed by #9 

Major2:
Added also a reference to the oid draft and considerations on ibgp or within administrative boundaries.

Old:/ Where the above mechanisms are not in place, this would open the door
to further denial-of-service attacks such as unwanted traffic filtering,
remarking or redirection./
New: / Where the above mechanisms are not in place, this could open the door
to furhter denial-of-service attacks such as unwanted traffic filtering,
remarking, or redirection.

One proposal for relaxing the above mechanisms within the administrative
boundaries of AS via ibgp is included in [draft-ietf-idr-bgp-oid].
Deployment of such specific relaxation of validation within an
adminstrative boundary of a network defined by an AS or an
AS-Confederation boundary may useful in some network in
quickly distributing filters to prevent denial-of-service attacks.
For a network to utilize this relaxation, the BGP policies must
support additional filtering since the the origin as field is empty.
Specifications relaxing the validation restrictions SHOULD
contain security considerations that provide details on the
required additional filtering.

**Comment by stoffi92** [comment]
//doc
Major1:
Has been addressed by #9

Major2:
In the iBGP case we are basically validating ourselves (see the introduction). Compared to iBGP for ipv4 unicast: Our iBGP neighbors or RRs are usually part of my own trust domain. We usually care about what we receive from outside our administrative domain (ig. eBGP). Furthermore in the iBGP case we do not have any origin AS to verify against. However, the rough system case - that you pointed out, is now addressed in the security considerations.
