### ISSUE TITLE
811	7.  Traffic Filtering Actions

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#63]
811	7.  Traffic Filtering Actions
...
820	   Implementations SHOULD provide mechanisms that map an arbitrary BGP
821	   community value (normal or extended) to filtering actions that
822	   require different mappings in different systems in the network.  For
823	   instance, providing packets with a worse-than-best-effort, per-hop
824	   behavior is a functionality that is likely to be implemented
825	   differently in different systems and for which no standard behavior
826	   is currently known.  Rather than attempting to define it here, this
827	   can be accomplished by mapping a user-defined community value to
828	   platform-/network-specific behavior via user configuration.

[major] While this paragraph sounds technically correct, I think it doesn't belong in this document because it (randomly) talks about a different, yet tangentially related, topic.  Also, it basically says "SHOULD provide a mechanism to take arbitrary actions...which are not defined here", so it is not complete from a Normative point of view.  I would prefer if we took this paragraph out.

**Comment by stoffi92** [comment]
I think that this fits well into the picture. It just says, that arbitrary mapping of other (non specified by this document) communities to filtering actions (specified by this document or not) should be provided. This is usually the case with the BGP policy-frameworks provided by the vendors (route-maps, policy-options policy-statement). Additionally other filter actions may be provided (but are vendor/network/implementation specific)... 

A example comes in mind: maybe I want to provide a community for rate-limit to my customers that sets a bigger burst-size than the standard rate-limit community. If my plattform supports matching communities to arbitrary feature actions I could do something like this.

I actually saw that quite a few times because depending on the place in the network one may want to apply different actions that get triggered by the same bgp-community (and rewritten to a node specific action).

**Comment by suehares** [comment]
Alvaro is correct.  This text is not normative.  

We can add a manageability section or put this text in an accompanying application document.

**Comment by raszuk** [comment]
The original RFC5575 allowed to integrated flow-spec rules with any other filtering rules on the box by stating: 

   Implementations should provide mechanisms that map an arbitrary BGP
   community value (normal or extended) to filtering actions that
   require different mappings in different systems in the network.  For
   instance, providing packets with a worse-than-best-effort, per-hop
   behavior is a functionality that is likely to be implemented
   differently in different systems and for which no standard behavior
   is currently known.  Rather than attempting to define it here, this
   can be accomplished by mapping a user-defined community value to
   platform-/network-specific behavior via user configuration.

We can not just remove it now as it will break implementations. The text is not normative in a sense that it does not enumerate endless filtering combinations, but it should stay in this spec to make sure implementations can handle flow-spec filtering in concert with any other filtering enable by the operator.

**Comment by suehares** [comment]
Ok - we need to leave it to keep interoperability. 

The best way to handle it is to create a new section in the body of the text with a clear title.
One way is to create a 7.1 section with 

7.1 Interaction of flow specification filters with other filtering rules in router 

Move the paragraph above in question out of the top and into this section.

This approach can fix Alvaro's issue as we are clearly stating what is being standardized.

**Comment by suehares** [comment]
Christoph - wait until Robert agrees in order to close this issue

**Comment by raszuk** [comment]
Sounds good to me.

Thx

**Comment by stoffi92** [comment]
/doc
We need this to keep interoperability but added a new section on "Interaction with other Filtering Mechanisms in Routers"
